export { tokenize, TokenType, type Token } from "./lexer.js";
export {
  parse,
  ParseError,
  NodeType,
  type TemplateAST,
  type TypeDirective,
  type ASTNode,
  type ExprNode,
  type TextNode,
  type ExpressionNode,
  type RawExpressionNode,
  type IdentifierNode,
  type PropertyAccessNode,
  type BinaryExpressionNode,
  type UnaryExpressionNode,
  type StringLiteralNode,
  type NumberLiteralNode,
  type IfBlockNode,
  type ForBlockNode,
  type SwitchBlockNode,
  type CommentNode,
  type PartialNode,
  type MetaVariableNode,
} from "./parser.js";
export {
  TypeKind,
  formatType,
  formatTypeDefinition,
  type Type,
  type TString,
  type TNumber,
  type TBoolean,
  type TNull,
  type TUndefined,
  type TAny,
  type TArray,
  type TObject,
  type TUnion,
  type TStringLiteral,
  type TNumberLiteral,
  type TBooleanLiteral,
} from "./types.js";
export { typecheck, type Diagnostic } from "./checker.js";
export { typeAtPosition, type HoverResult } from "./hover.js";
export { resolveType } from "./resolver.js";
